#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Apr 02 00:58:17 +0530 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_bootloader_instmem_behav -key {Behavioral:sim_1:Functional:tb_bootloader_instmem} -tclbatch tb_bootloader_instmem.tcl -log simulate.log"
xsim tb_bootloader_instmem_behav -key {Behavioral:sim_1:Functional:tb_bootloader_instmem} -tclbatch tb_bootloader_instmem.tcl -log simulate.log

