#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 07 21:22:19 +0530 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_result_writer_behav -key {Behavioral:sim_1:Functional:tb_result_writer} -tclbatch tb_result_writer.tcl -log simulate.log"
xsim tb_result_writer_behav -key {Behavioral:sim_1:Functional:tb_result_writer} -tclbatch tb_result_writer.tcl -log simulate.log

