#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 27 23:02:16 +0530 2026
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -log simulate.log"
xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -log simulate.log

