`ifndef MEMORY_DEFINES_VH
`define MEMORY_DEFINES_VH

`define WORD_SIZE 32

// Instruction memory
`define INST_ROM_BASE_ADDRESS         32'h00000000
`define INSTRUCTION_MEMORY_SIZE_BYTES 1540
`define INSTRUCTION_MEMORY_SIZE_WORDS (`INSTRUCTION_MEMORY_SIZE_BYTES / 4)

// Data ROM
`define DATA_ROM_BASE_ADDRESS         32'h01000000
`define DATA_ROM_MEMORY_SIZE_BYTES    8
`define DATA_ROM_MEMORY_SIZE_WORDS    (`DATA_ROM_MEMORY_SIZE_BYTES / 4)

// Data RAM
`define DATA_RAM_BASE_ADDRESS         32'h02000000
`define DATA_RAM_MEMORY_SIZE_BYTES    4096
`define DATA_RAM_MEMORY_SIZE_WORDS    (`DATA_RAM_MEMORY_SIZE_BYTES / 4)

`endif